# Errors

```ts title="server.ts"
const isAuthed = middleware(({ ctx, next }) => {
  if (!ctx.user) throw new HTTPError({ code: 'UNAUTHORIZED', message: 'Must be logged in!' });

  return next({
    ...ctx,
    user: ctx.user,
  });
});
```

The `HTTPError` is the only error that is catched by the `ptsq`.
The adapter such as `Express` or `Koa` then reponse with that error code and message, if specified.
You can also specify info, which is anything you want. It won't be displayed in the response message, it is for developers only, can be something like schema validation error or something like that.

```ts
throw new HTTPError({ code: 'BAD_REQUEST', message: 'User already exists.', info: databaseInsert.error });
```

## Error codes

| HTTPError code        | Status code |
| --------------------- | ----------- |
| BAD_REQUEST           | 400         |
| UNAUTHORIZED          | 401         |
| FORBIDDEN             | 403         |
| NOT_FOUND             | 404         |
| METHOD_NOT_SUPPORTED  | 405         |
| TIMEOUT               | 408         |
| CONFLICT              | 409         |
| PRECONDITION_FAILED   | 412         |
| PAYLOAD_TOO_LARGE     | 413         |
| UNPROCESSABLE_CONTENT | 422         |
| TOO_MANY_REQUESTS     | 429         |
| CLIENT_CLOSED_REQUEST | 499         |
| INTERNAL_SERVER_ERROR | 500         |

Any other thrown exception that is not a `HTTPError`, throws as normal, so it can stops the running server.
